// DcomSvr.idl : IDL source for DcomSvr.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (DcomSvr.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(F5648F39-3FCF-49BD-BC84-1A52BEAC849E),
		dual,
		helpstring("IMyObject Interface"),
		pointer_default(unique)
	]
	interface IMyObject : IDispatch
	{
		[id(1), helpstring("method GetData")] HRESULT GetData([out]long* lpData);
	};

[
	uuid(F51B86B6-EF5B-494D-9FB8-6140D65E2CB4),
	version(1.0),
	helpstring("DcomSvr 1.0 Type Library")
]
library DCOMSVRLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(C6EDEC7B-B9AB-45CB-8090-1589F3E47283),
		helpstring("MyObject Class")
	]
	coclass MyObject
	{
		[default] interface IMyObject;
	};
};
